import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Stream Video SDK styles
// package provides `styles.css` under `dist/css` (not `index.css`)
import "@stream-io/video-react-sdk/dist/css/styles.css";
import { Toaster } from "@/components/ui/sonner";
import { TRPCProvider } from "@/trpc/client";
import { NuqsAdapter } from 'nuqs/adapters/next/app';
const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <html lang="en">
        <body
          className={`${inter.className} antialiased`}
        >
          <TRPCProvider>
            {children}
            <Toaster position="top-center" />
          </TRPCProvider>
        </body>
      </html>
    </NuqsAdapter>
  );
}
